echo "too lazy to do this right now"
echo "add .bash_aliases to top of your bashrc"

echo "" >>  ~/.bashrc
echo "# --- Autogenerated from my config script ---" >> ~/.bashrc
echo "source ~/.config/bash_after" >> ~/.bashrc
echo "# --- End autogenerated section ---" >> ~/.bashrc
